# Source: configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: m8-httpserver
  namespace: default
  labels:
    app.kubernetes.io/name: httpserver
    app.kubernetes.io/instance: m8
    app.kubernetes.io/managed-by: Manual
data:
  config.yaml: |-
    http:
      port: 8080
      host: 0.0.0.0

    log:
      level: info